// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: file.proto
// Protobuf Java Version: 4.29.3

package com.diaoling.schema.file;

import com.google.protobuf.*;

import java.util.Map;

public final class FileSchema {
    private FileSchema() {
    }

    static {
        RuntimeVersion.validateProtobufGencodeVersion(
                RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 29,
                /* patch= */ 3,
                /* suffix= */ "",
                FileSchema.class.getName());
    }

    public static void registerAllExtensions(
            ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            ExtensionRegistry registry) {
        registerAllExtensions(
                (ExtensionRegistryLite) registry);
    }

    /**
     * Protobuf enum {@code com.diaoling.schema.FileType}
     */
    public enum FileType
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>UNKNOWN_FILE = 0;</code>
         */
        UNKNOWN_FILE(0),
        /**
         * <code>SETTINGS_CONFIG_FILE = 1;</code>
         */
        SETTINGS_CONFIG_FILE(1),
        /**
         * <code>MODULE_CONFIG_FILE = 2;</code>
         */
        MODULE_CONFIG_FILE(2),
        /**
         * <code>CLIENT_CONFIG_FILE = 3;</code>
         */
        CLIENT_CONFIG_FILE(3),
        UNRECOGNIZED(-1),
        ;

        static {
            RuntimeVersion.validateProtobufGencodeVersion(
                    RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 29,
                    /* patch= */ 3,
                    /* suffix= */ "",
                    FileType.class.getName());
        }

        /**
         * <code>UNKNOWN_FILE = 0;</code>
         */
        public static final int UNKNOWN_FILE_VALUE = 0;
        /**
         * <code>SETTINGS_CONFIG_FILE = 1;</code>
         */
        public static final int SETTINGS_CONFIG_FILE_VALUE = 1;
        /**
         * <code>MODULE_CONFIG_FILE = 2;</code>
         */
        public static final int MODULE_CONFIG_FILE_VALUE = 2;
        /**
         * <code>CLIENT_CONFIG_FILE = 3;</code>
         */
        public static final int CLIENT_CONFIG_FILE_VALUE = 3;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static FileType valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static FileType forNumber(int value) {
            switch (value) {
                case 0:
                    return UNKNOWN_FILE;
                case 1:
                    return SETTINGS_CONFIG_FILE;
                case 2:
                    return MODULE_CONFIG_FILE;
                case 3:
                    return CLIENT_CONFIG_FILE;
                default:
                    return null;
            }
        }

        public static Internal.EnumLiteMap<FileType>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final Internal.EnumLiteMap<
                FileType> internalValueMap =
                new Internal.EnumLiteMap<FileType>() {
                    public FileType findValueByNumber(int number) {
                        return FileType.forNumber(number);
                    }
                };

        public final Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            if (this == UNRECOGNIZED) {
                throw new IllegalStateException(
                        "Can't get the descriptor of an unrecognized enum value.");
            }
            return getDescriptor().getValues().get(ordinal());
        }

        public final Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final Descriptors.EnumDescriptor
        getDescriptor() {
            return FileSchema.getDescriptor().getEnumTypes().get(0);
        }

        private static final FileType[] VALUES = values();

        public static FileType valueOf(
                Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private FileType(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:com.diaoling.schema.FileType)
    }

    public interface BaseFileOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.diaoling.schema.BaseFile)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>map&lt;string, string&gt; metadata = 1;</code>
         */
        int getMetadataCount();

        /**
         * <code>map&lt;string, string&gt; metadata = 1;</code>
         */
        boolean containsMetadata(
                java.lang.String key);

        /**
         * Use {@link #getMetadataMap()} instead.
         */
        @java.lang.Deprecated
        Map<String, String>
        getMetadata();

        /**
         * <code>map&lt;string, string&gt; metadata = 1;</code>
         */
        Map<java.lang.String, java.lang.String>
        getMetadataMap();

        /**
         * <code>map&lt;string, string&gt; metadata = 1;</code>
         */
        /* nullable */
        String getMetadataOrDefault(
                java.lang.String key,
                /* nullable */
                java.lang.String defaultValue);

        /**
         * <code>map&lt;string, string&gt; metadata = 1;</code>
         */
        String getMetadataOrThrow(
                java.lang.String key);

        /**
         * <code>.com.diaoling.schema.FileType type = 2;</code>
         *
         * @return The enum numeric value on the wire for type.
         */
        int getTypeValue();

        /**
         * <code>.com.diaoling.schema.FileType type = 2;</code>
         *
         * @return The type.
         */
        FileSchema.FileType getType();

        /**
         * <code>int64 created_time = 3;</code>
         *
         * @return The createdTime.
         */
        long getCreatedTime();

        /**
         * <code>int64 modified_time = 4;</code>
         *
         * @return The modifiedTime.
         */
        long getModifiedTime();

        /**
         * <code>bytes context = 5;</code>
         *
         * @return The context.
         */
        com.google.protobuf.ByteString getContext();
    }

    /**
     * Protobuf type {@code com.diaoling.schema.BaseFile}
     */
    public static final class BaseFile extends
            GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:com.diaoling.schema.BaseFile)
            BaseFileOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            RuntimeVersion.validateProtobufGencodeVersion(
                    RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 29,
                    /* patch= */ 3,
                    /* suffix= */ "",
                    BaseFile.class.getName());
        }

        // Use BaseFile.newBuilder() to construct.
        private BaseFile(GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private BaseFile() {
            type_ = 0;
            context_ = ByteString.EMPTY;
        }

        public static final Descriptors.Descriptor
        getDescriptor() {
            return FileSchema.internal_static_com_diaoling_schema_BaseFile_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        @java.lang.Override
        protected MapFieldReflectionAccessor internalGetMapFieldReflection(
                int number) {
            switch (number) {
                case 1:
                    return internalGetMetadata();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.diaoling.schema.file.FileSchema.internal_static_com_diaoling_schema_BaseFile_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.diaoling.schema.file.FileSchema.BaseFile.class, com.diaoling.schema.file.FileSchema.BaseFile.Builder.class);
        }

        public static final int METADATA_FIELD_NUMBER = 1;

        private static final class MetadataDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, java.lang.String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, java.lang.String>newDefaultInstance(
                                    com.diaoling.schema.file.FileSchema.internal_static_com_diaoling_schema_BaseFile_MetadataEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }

        @SuppressWarnings("serial")
        private com.google.protobuf.MapField<
                java.lang.String, java.lang.String> metadata_;

        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMetadata() {
            if (metadata_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        MetadataDefaultEntryHolder.defaultEntry);
            }
            return metadata_;
        }

        public int getMetadataCount() {
            return internalGetMetadata().getMap().size();
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 1;</code>
         */
        @java.lang.Override
        public boolean containsMetadata(
                java.lang.String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            return internalGetMetadata().getMap().containsKey(key);
        }

        /**
         * Use {@link #getMetadataMap()} instead.
         */
        @java.lang.Override
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
            return getMetadataMap();
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 1;</code>
         */
        @java.lang.Override
        public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
            return internalGetMetadata().getMap();
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 1;</code>
         */
        @java.lang.Override
        public /* nullable */
        java.lang.String getMetadataOrDefault(
                java.lang.String key,
                /* nullable */
                java.lang.String defaultValue) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetMetadata().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 1;</code>
         */
        @java.lang.Override
        public java.lang.String getMetadataOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetMetadata().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        public static final int TYPE_FIELD_NUMBER = 2;
        private int type_ = 0;

        /**
         * <code>.com.diaoling.schema.FileType type = 2;</code>
         *
         * @return The enum numeric value on the wire for type.
         */
        @java.lang.Override
        public int getTypeValue() {
            return type_;
        }

        /**
         * <code>.com.diaoling.schema.FileType type = 2;</code>
         *
         * @return The type.
         */
        @java.lang.Override
        public com.diaoling.schema.file.FileSchema.FileType getType() {
            com.diaoling.schema.file.FileSchema.FileType result = com.diaoling.schema.file.FileSchema.FileType.forNumber(type_);
            return result == null ? com.diaoling.schema.file.FileSchema.FileType.UNRECOGNIZED : result;
        }

        public static final int CREATED_TIME_FIELD_NUMBER = 3;
        private long createdTime_ = 0L;

        /**
         * <code>int64 created_time = 3;</code>
         *
         * @return The createdTime.
         */
        @java.lang.Override
        public long getCreatedTime() {
            return createdTime_;
        }

        public static final int MODIFIED_TIME_FIELD_NUMBER = 4;
        private long modifiedTime_ = 0L;

        /**
         * <code>int64 modified_time = 4;</code>
         *
         * @return The modifiedTime.
         */
        @java.lang.Override
        public long getModifiedTime() {
            return modifiedTime_;
        }

        public static final int CONTEXT_FIELD_NUMBER = 5;
        private com.google.protobuf.ByteString context_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes context = 5;</code>
         *
         * @return The context.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getContext() {
            return context_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            com.google.protobuf.GeneratedMessage
                    .serializeStringMapTo(
                            output,
                            internalGetMetadata(),
                            MetadataDefaultEntryHolder.defaultEntry,
                            1);
            if (type_ != com.diaoling.schema.file.FileSchema.FileType.UNKNOWN_FILE.getNumber()) {
                output.writeEnum(2, type_);
            }
            if (createdTime_ != 0L) {
                output.writeInt64(3, createdTime_);
            }
            if (modifiedTime_ != 0L) {
                output.writeInt64(4, modifiedTime_);
            }
            if (!context_.isEmpty()) {
                output.writeBytes(5, context_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
                    : internalGetMetadata().getMap().entrySet()) {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                        metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, metadata__);
            }
            if (type_ != com.diaoling.schema.file.FileSchema.FileType.UNKNOWN_FILE.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(2, type_);
            }
            if (createdTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(3, createdTime_);
            }
            if (modifiedTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(4, modifiedTime_);
            }
            if (!context_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, context_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.diaoling.schema.file.FileSchema.BaseFile)) {
                return super.equals(obj);
            }
            com.diaoling.schema.file.FileSchema.BaseFile other = (com.diaoling.schema.file.FileSchema.BaseFile) obj;

            if (!internalGetMetadata().equals(
                    other.internalGetMetadata())) return false;
            if (type_ != other.type_) return false;
            if (getCreatedTime()
                    != other.getCreatedTime()) return false;
            if (getModifiedTime()
                    != other.getModifiedTime()) return false;
            if (!getContext()
                    .equals(other.getContext())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (!internalGetMetadata().getMap().isEmpty()) {
                hash = (37 * hash) + METADATA_FIELD_NUMBER;
                hash = (53 * hash) + internalGetMetadata().hashCode();
            }
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + type_;
            hash = (37 * hash) + CREATED_TIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getCreatedTime());
            hash = (37 * hash) + MODIFIED_TIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getModifiedTime());
            hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
            hash = (53 * hash) + getContext().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.diaoling.schema.file.FileSchema.BaseFile parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.diaoling.schema.file.FileSchema.BaseFile parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.diaoling.schema.file.FileSchema.BaseFile parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.diaoling.schema.file.FileSchema.BaseFile parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.diaoling.schema.file.FileSchema.BaseFile parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.diaoling.schema.file.FileSchema.BaseFile parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.diaoling.schema.file.FileSchema.BaseFile parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static com.diaoling.schema.file.FileSchema.BaseFile parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.diaoling.schema.file.FileSchema.BaseFile parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.diaoling.schema.file.FileSchema.BaseFile parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.diaoling.schema.file.FileSchema.BaseFile parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static com.diaoling.schema.file.FileSchema.BaseFile parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.diaoling.schema.file.FileSchema.BaseFile prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code com.diaoling.schema.BaseFile}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.diaoling.schema.BaseFile)
                com.diaoling.schema.file.FileSchema.BaseFileOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.diaoling.schema.file.FileSchema.internal_static_com_diaoling_schema_BaseFile_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetMetadata();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetMutableMetadata();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.diaoling.schema.file.FileSchema.internal_static_com_diaoling_schema_BaseFile_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.diaoling.schema.file.FileSchema.BaseFile.class, com.diaoling.schema.file.FileSchema.BaseFile.Builder.class);
            }

            // Construct using com.diaoling.schema.file.FileSchema.BaseFile.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                internalGetMutableMetadata().clear();
                type_ = 0;
                createdTime_ = 0L;
                modifiedTime_ = 0L;
                context_ = com.google.protobuf.ByteString.EMPTY;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.diaoling.schema.file.FileSchema.internal_static_com_diaoling_schema_BaseFile_descriptor;
            }

            @java.lang.Override
            public com.diaoling.schema.file.FileSchema.BaseFile getDefaultInstanceForType() {
                return com.diaoling.schema.file.FileSchema.BaseFile.getDefaultInstance();
            }

            @java.lang.Override
            public com.diaoling.schema.file.FileSchema.BaseFile build() {
                com.diaoling.schema.file.FileSchema.BaseFile result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.diaoling.schema.file.FileSchema.BaseFile buildPartial() {
                com.diaoling.schema.file.FileSchema.BaseFile result = new com.diaoling.schema.file.FileSchema.BaseFile(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(com.diaoling.schema.file.FileSchema.BaseFile result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.metadata_ = internalGetMetadata();
                    result.metadata_.makeImmutable();
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.type_ = type_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.createdTime_ = createdTime_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.modifiedTime_ = modifiedTime_;
                }
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.context_ = context_;
                }
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.diaoling.schema.file.FileSchema.BaseFile) {
                    return mergeFrom((com.diaoling.schema.file.FileSchema.BaseFile) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.diaoling.schema.file.FileSchema.BaseFile other) {
                if (other == com.diaoling.schema.file.FileSchema.BaseFile.getDefaultInstance()) return this;
                internalGetMutableMetadata().mergeFrom(
                        other.internalGetMetadata());
                bitField0_ |= 0x00000001;
                if (other.type_ != 0) {
                    setTypeValue(other.getTypeValue());
                }
                if (other.getCreatedTime() != 0L) {
                    setCreatedTime(other.getCreatedTime());
                }
                if (other.getModifiedTime() != 0L) {
                    setModifiedTime(other.getModifiedTime());
                }
                if (other.getContext() != com.google.protobuf.ByteString.EMPTY) {
                    setContext(other.getContext());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                                        metadata__ = input.readMessage(
                                        MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                                internalGetMutableMetadata().getMutableMap().put(
                                        metadata__.getKey(), metadata__.getValue());
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 16: {
                                type_ = input.readEnum();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 16
                            case 24: {
                                createdTime_ = input.readInt64();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 24
                            case 32: {
                                modifiedTime_ = input.readInt64();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 32
                            case 42: {
                                context_ = input.readBytes();
                                bitField0_ |= 0x00000010;
                                break;
                            } // case 42
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.MapField<
                    java.lang.String, java.lang.String> metadata_;

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetMetadata() {
                if (metadata_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            MetadataDefaultEntryHolder.defaultEntry);
                }
                return metadata_;
            }

            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetMutableMetadata() {
                if (metadata_ == null) {
                    metadata_ = com.google.protobuf.MapField.newMapField(
                            MetadataDefaultEntryHolder.defaultEntry);
                }
                if (!metadata_.isMutable()) {
                    metadata_ = metadata_.copy();
                }
                bitField0_ |= 0x00000001;
                onChanged();
                return metadata_;
            }

            public int getMetadataCount() {
                return internalGetMetadata().getMap().size();
            }

            /**
             * <code>map&lt;string, string&gt; metadata = 1;</code>
             */
            @java.lang.Override
            public boolean containsMetadata(
                    java.lang.String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                return internalGetMetadata().getMap().containsKey(key);
            }

            /**
             * Use {@link #getMetadataMap()} instead.
             */
            @java.lang.Override
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
                return getMetadataMap();
            }

            /**
             * <code>map&lt;string, string&gt; metadata = 1;</code>
             */
            @java.lang.Override
            public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
                return internalGetMetadata().getMap();
            }

            /**
             * <code>map&lt;string, string&gt; metadata = 1;</code>
             */
            @java.lang.Override
            public /* nullable */
            java.lang.String getMetadataOrDefault(
                    java.lang.String key,
                    /* nullable */
                    java.lang.String defaultValue) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetMetadata().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <code>map&lt;string, string&gt; metadata = 1;</code>
             */
            @java.lang.Override
            public java.lang.String getMetadataOrThrow(
                    java.lang.String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetMetadata().getMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearMetadata() {
                bitField0_ = (bitField0_ & ~0x00000001);
                internalGetMutableMetadata().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <code>map&lt;string, string&gt; metadata = 1;</code>
             */
            public Builder removeMetadata(
                    java.lang.String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                internalGetMutableMetadata().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String>
            getMutableMetadata() {
                bitField0_ |= 0x00000001;
                return internalGetMutableMetadata().getMutableMap();
            }

            /**
             * <code>map&lt;string, string&gt; metadata = 1;</code>
             */
            public Builder putMetadata(
                    java.lang.String key,
                    java.lang.String value) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                if (value == null) {
                    throw new NullPointerException("map value");
                }
                internalGetMutableMetadata().getMutableMap()
                        .put(key, value);
                bitField0_ |= 0x00000001;
                return this;
            }

            /**
             * <code>map&lt;string, string&gt; metadata = 1;</code>
             */
            public Builder putAllMetadata(
                    java.util.Map<java.lang.String, java.lang.String> values) {
                internalGetMutableMetadata().getMutableMap()
                        .putAll(values);
                bitField0_ |= 0x00000001;
                return this;
            }

            private int type_ = 0;

            /**
             * <code>.com.diaoling.schema.FileType type = 2;</code>
             *
             * @return The enum numeric value on the wire for type.
             */
            @java.lang.Override
            public int getTypeValue() {
                return type_;
            }

            /**
             * <code>.com.diaoling.schema.FileType type = 2;</code>
             *
             * @param value The enum numeric value on the wire for type to set.
             * @return This builder for chaining.
             */
            public Builder setTypeValue(int value) {
                type_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>.com.diaoling.schema.FileType type = 2;</code>
             *
             * @return The type.
             */
            @java.lang.Override
            public com.diaoling.schema.file.FileSchema.FileType getType() {
                com.diaoling.schema.file.FileSchema.FileType result = com.diaoling.schema.file.FileSchema.FileType.forNumber(type_);
                return result == null ? com.diaoling.schema.file.FileSchema.FileType.UNRECOGNIZED : result;
            }

            /**
             * <code>.com.diaoling.schema.FileType type = 2;</code>
             *
             * @param value The type to set.
             * @return This builder for chaining.
             */
            public Builder setType(com.diaoling.schema.file.FileSchema.FileType value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                type_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>.com.diaoling.schema.FileType type = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearType() {
                bitField0_ = (bitField0_ & ~0x00000002);
                type_ = 0;
                onChanged();
                return this;
            }

            private long createdTime_;

            /**
             * <code>int64 created_time = 3;</code>
             *
             * @return The createdTime.
             */
            @java.lang.Override
            public long getCreatedTime() {
                return createdTime_;
            }

            /**
             * <code>int64 created_time = 3;</code>
             *
             * @param value The createdTime to set.
             * @return This builder for chaining.
             */
            public Builder setCreatedTime(long value) {

                createdTime_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>int64 created_time = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCreatedTime() {
                bitField0_ = (bitField0_ & ~0x00000004);
                createdTime_ = 0L;
                onChanged();
                return this;
            }

            private long modifiedTime_;

            /**
             * <code>int64 modified_time = 4;</code>
             *
             * @return The modifiedTime.
             */
            @java.lang.Override
            public long getModifiedTime() {
                return modifiedTime_;
            }

            /**
             * <code>int64 modified_time = 4;</code>
             *
             * @param value The modifiedTime to set.
             * @return This builder for chaining.
             */
            public Builder setModifiedTime(long value) {

                modifiedTime_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>int64 modified_time = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearModifiedTime() {
                bitField0_ = (bitField0_ & ~0x00000008);
                modifiedTime_ = 0L;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString context_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes context = 5;</code>
             *
             * @return The context.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getContext() {
                return context_;
            }

            /**
             * <code>bytes context = 5;</code>
             *
             * @param value The context to set.
             * @return This builder for chaining.
             */
            public Builder setContext(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                context_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>bytes context = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearContext() {
                bitField0_ = (bitField0_ & ~0x00000010);
                context_ = getDefaultInstance().getContext();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.diaoling.schema.BaseFile)
        }

        // @@protoc_insertion_point(class_scope:com.diaoling.schema.BaseFile)
        private static final com.diaoling.schema.file.FileSchema.BaseFile DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.diaoling.schema.file.FileSchema.BaseFile();
        }

        public static com.diaoling.schema.file.FileSchema.BaseFile getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<BaseFile>
                PARSER = new com.google.protobuf.AbstractParser<BaseFile>() {
            @java.lang.Override
            public BaseFile parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<BaseFile> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<BaseFile> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.diaoling.schema.file.FileSchema.BaseFile getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_diaoling_schema_BaseFile_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_com_diaoling_schema_BaseFile_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_diaoling_schema_BaseFile_MetadataEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_com_diaoling_schema_BaseFile_MetadataEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\nfile.proto\022\023com.diaoling.schema\"\345\001\n\010Ba" +
                        "seFile\022=\n\010metadata\030\001 \003(\0132+.com.diaoling." +
                        "schema.BaseFile.MetadataEntry\022+\n\004type\030\002 " +
                        "\001(\0162\035.com.diaoling.schema.FileType\022\024\n\014cr" +
                        "eated_time\030\003 \001(\003\022\025\n\rmodified_time\030\004 \001(\003\022" +
                        "\017\n\007context\030\005 \001(\014\032/\n\rMetadataEntry\022\013\n\003key" +
                        "\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*f\n\010FileType\022\020\n" +
                        "\014UNKNOWN_FILE\020\000\022\030\n\024SETTINGS_CONFIG_FILE\020" +
                        "\001\022\026\n\022MODULE_CONFIG_FILE\020\002\022\026\n\022CLIENT_CONF" +
                        "IG_FILE\020\003B&\n\030com.diaoling.schema.fileB\nF" +
                        "ileSchemab\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_com_diaoling_schema_BaseFile_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_diaoling_schema_BaseFile_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_com_diaoling_schema_BaseFile_descriptor,
                new java.lang.String[]{"Metadata", "Type", "CreatedTime", "ModifiedTime", "Context",});
        internal_static_com_diaoling_schema_BaseFile_MetadataEntry_descriptor =
                internal_static_com_diaoling_schema_BaseFile_descriptor.getNestedTypes().get(0);
        internal_static_com_diaoling_schema_BaseFile_MetadataEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_com_diaoling_schema_BaseFile_MetadataEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
